### ISSUE TITLE
xlsx package does not work in R 3.4

### ISSUE THREAD

**Issue by fritsander** [colearendt/xlsx#82]
Hi, I've been using xlsx in R 3.3.3 without any problems. After upgrading to the latest RStudio and R 3.4.0 xlsx stopped working because it cannot load the rJava package. Please help.

Thanks in advance.

Fritsander

**Comment by zeehio** [comment]
I am using R-3.4.0 with xlsx without issues. I installed rJava using `sudo apt-get install r-cran-rjava`. I hope this helps you.

**Comment by fritsander** [comment]
Do I run this from within R? Or do I need Terminal to do it? I use a standard user account on my MacBook Pro. Thanks again.

**Comment by colearendt** [comment]
@fritsander Did you reinstall the rJava package?  What error messages do you get on load / install?

**Comment by fritsander** [comment]
Hi,

I reinstalled rJava and the xlsx package. When running library(xlsx) in R I get the following error message:

Loading required package: rJava
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Users/lahr/Library/R/3.4/library/rJava/libs/rJava.so':
  dlopen(/Users/lahr/Library/R/3.4/library/rJava/libs/rJava.so, 6): Library not loaded: @rpath/libjvm.dylib
  Referenced from: /Users/lahr/Library/R/3.4/library/rJava/libs/rJava.so
  Reason: image not found
Error: package ‘rJava’ could not be loaded

From this point on I’m puzzled.

Kind regards,



Fritsander Lahr



On 10 Jun 2017 (23), at 12:59, Cole Arendt <notifications@github.com<mailto:notifications@github.com>> wrote:


@fritsander<https://github.com/fritsander> Did you reinstall the rJava package? What error messages do you get on load / install?

**Comment by colearendt** [comment]
This may be a silly question, but it sounds like you may not have the Java `jdk` installed and available on your `PATH`?  `rJava` only has a dependency on Java, which must be installed separately.  Not sure if the update of R may have caused an issue with your java configuration - perhaps the `javareconf` mentioned on the `rJava` page is in order.

See details on installation of rJava [here](https://www.rforge.net/rJava/) (see the "Installation" header)

Downloads of various JDKs can be found [here](http://www.oracle.com/technetwork/java/javase/downloads/index.html)

**Comment by colearendt** [comment]
Any progress on resolving this? Having same issue finding libjvm.dylib on Travis CI for OSX and R 3.4.

**Comment by colearendt** [comment]
Another thing may be to ensure JAVA_HOME is set properly, as the problem looks to be in rJava and Java configuration

**Comment by colearendt** [comment]
Fixed on Travis CI by using `sudo R CMD javareconf` to ensure that java was configured properly with R.  Note, per discussions above, that this is done from the terminal, not from within R.

**Comment by fritsander** [comment]
I ran the command sudo R CMD javareconf in the terminal. This seemed to be succesful, but did not solve the problem.

How do I set the JAVA_HOME properly?

Kind regards
Fritsander Lahr



On 20 Jun 2017 (25), at 21:14, Cole Arendt <notifications@github.com<mailto:notifications@github.com>> wrote:

sudo R CMD javareconf

**Comment by colearendt** [comment]
See if this can be helpful : https://www.mkyong.com/java/how-to-set-java_home-environment-variable-on-mac-os-x/

You may need to rerun the Java reconf after setting, as I am not sure how they interact.  

You can tell if the variable is set from a new R session with Sys.getenv(). More docs can be found by searching for setting environment variables.

**Comment by fritsander** [comment]
When running Sys.getenv() from within R what should the JAVA_HOME variable look like?

Thanks.

Fritsander Lahr



On 21 Jun 2017 (25), at 19:15, Cole Arendt <notifications@github.com<mailto:notifications@github.com>> wrote:

Sys.getenv()

**Comment by colearendt** [comment]
Depends on your OS and install of jdk.  Should be a file system path ending in /jdk_xxx/ or something like that, I think.

**Comment by fritsander** [comment]
So, something like JAVA_HOME = …../jdk_xxx/…..?


Fritsander Lahr



On 21 Jun 2017 (25), at 21:03, Cole Arendt <notifications@github.com<mailto:notifications@github.com>> wrote:

Depends on your OS and install of jdk. Should be a file system path ending in /jdk_xxx/ or something like that, I think.

**Comment by colearendt** [comment]
No, not so literally.  Did you read the article I mentioned?  https://www.mkyong.com/java/how-to-set-java_home-environment-variable-on-mac-os-x/

Mine is (on terminal):
```
echo $JAVA_HOME
/usr/local/java/jdk1.8.0_91
```

It can be set temporarily with
```
SET JAVA_HOME=/usr/local/java/jdk1.8.0_91
```

To set more permanently and allow it to be picked up by R, you need to set it in a `.bashrc` file usually, but the article explains in more detail.

**Comment by colearendt** [comment]
This is `rJava` and java configuration related and not the fault of the `xlsx` package.  Closing.
